services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:newpassword@db:5432/example
      - ADMIN_PASSWORD_HASH=342df5b036b2f28184536820af6d1caf
    command: fastapi dev app.py --host 0.0.0.0 --reload
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=newpassword
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
